# Generated by Django 4.0.5 on 2023-05-23 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['id']},
        ),
    ]
