# Generated by Django 4.0.5 on 2023-05-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_artist_options_alter_music_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
