# Generated by Django 4.0.5 on 2023-05-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_image_playlist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='image',
        ),
        migrations.AddField(
            model_name='music',
            name='lyrics',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
