# Generated by Django 4.0.5 on 2023-05-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_music_image_music_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='lyrics',
            field=models.TextField(null=True),
        ),
    ]
