# Generated by Django 4.0.5 on 2023-05-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_music_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='imageURL',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
