# Generated by Django 4.0.5 on 2023-05-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_playlist_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='imageURL',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
