# Generated by Django 4.0.5 on 2023-06-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_artist_genre_alter_music_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.CharField(max_length=100),
        ),
    ]
