# Generated by Django 4.0.5 on 2023-06-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_artist_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
