# Generated by Django 4.0.5 on 2023-06-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_alter_music_duration_alter_music_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
