# Generated by Django 4.0.5 on 2023-06-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_music_duration_alter_music_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='music',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='music',
            name='lyrics',
        ),
        migrations.AddField(
            model_name='music',
            name='subgenre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
